"""Research instructions. Scientific uncertainty is retained, never an execution gate."""
PROMPTS = {
'core': 'Read manuscript ONLY and independently choose 0–2 central scientific contributions. Assign core_id C01/C02, preserve exact manuscript sentences. No selectable core is a valid status; it differs from an extraction failure. Do not infer from shared claims or method judgments.',
'core_mapping': 'Map each independently selected core to zero or more supplied shared claim IDs. Preserve core identity even if none match. Do not revise core selection.',
'review_sections': 'Segment the current review text into verbatim speaker sections, preserving role, explicit reviewer identity, round (0 unknown), manuscript scope. Previous sections provide context only; extract only current text. Include author/editor words separately.',
'checklist': 'Reconstruct reviewer scientific judgments and reasons, object, scope, round, reviewer and manuscript applicability from review sections and manuscript. Retain exact opinion and reason quotes, including positive judgments. Authors and editors are not reviewers; silence is not a negative. List named historical works without reviewer attitudes in prior_work_queries.',
'search': 'Plan at most four concise historical comparison keyword queries from manuscript; use scientific terms, not questions or wildcard punctuation. Extract explicitly cited works as cited_works (DOI if available, otherwise title). Do not use method conclusions or reviewer attitudes.',
'reference': 'For every core_id create historical reference R from manuscript and eligible historical source content only. States: supported_difference, substantially_covered, bounded_increment, insufficient_material. Distinguish common ground, actual difference and necessary scope; identify applicable comparison/scope cores. Target paper is not its own precedent. Missing retrieval is never firstness. Graph observations cannot establish historical novelty.',
'extract': 'Extract report atomic assertions verbatim with unit IDs, all shared-claim mentions and substantive status. Distinguish paraphrase and four nonparaphrase insight types. Separately extract P for every core_id: positive_increment, substantially_known, limited_increment, explicit_abstention, not_addressed. Keep ALL conflicting original quotes. Generic first/novel claims count as asserts_increment. Never supply missing answers or infer R.',
'support': 'Compare each supplied unit with actual source material. Return supported/partly_supported/not_verifiable/contradicted, scope correctness, exact source quotes/types/locations/scope/reasons. originally_substantiated means the ORIGINAL report already contained a usable locator supporting this assertion, not one found by this evaluation. Separate unsupported certainty, wrong antecedence, false firstness, similarity-as-causality and scope omission. Insufficient evidence is not contradicted.',
'novelty': 'Evaluate P against R, manuscript and sources for every core_id, recording V. Effective increment requires an explicit supported concrete difference, necessary scope and NO coexisting material overclaim. Generic firstness is an increment assertion but not an effective increment without concrete difference. Keep null when material is insufficient. Scope/comparison applicability comes from R; not_addressed is uncovered, not a negative scientific novelty conclusion.',
'concerns': 'Match every supplied human concern by object, scope and manuscript applicability. Score issue coverage separately from reason coverage. Preserve exact report quote and scientific disagreements: system_supported, system_error, review_unsubstantiated, unresolved. Silence is not a false positive.',
'quality_checklist': 'Build a neutral manuscript-and-source checklist for exactly five dimensions: contribution_fidelity, historical_increment, knowledge_relations, scope_uncertainty, whole_paper_synthesis. Use manuscript and historical sources only, no method reports or human attitude.',
'quality': 'Score exactly five checklist dimensions independently 0–3: 0 absent/materially incorrect; 1 partial with major gaps; 2 largely correct with bounded gaps; 3 faithful, specific and grounded. Cite report sentences and evidence, retain uncertainty. Never combine into a novelty total.',
'clusters': 'Partition anonymous supported substantive nonparaphrase assertions into scientific information clusters. Keep distinct increments distinct even if same topic. Classify historical_increment/cross_work_relation/scope_correction/cross_contribution. Each supplied unit should appear once. No method identities.',
'importance': 'Judge scientific importance of each anonymous cluster from manuscript and sources, not frequency, fluency or method. Return every cluster ID.',
'error_clusters': 'Cluster supplied anonymous erroneous assertions by same scientific error, preserving error category. Do not treat not_verifiable alone as error.',
'fusion': 'For each erroneous GEAR/Graph unit classify explicitly_corrected, not_propagated, propagated, unknown. Explicit correction needs a Full sentence actually correcting the error; absence alone is only not_propagated. Identify Full errors absent from both branches separately. Use source evidence and supplied error clusters.',
'preference': 'Compare anonymous reports A/B using manuscript and neutral common evidence. Overall and four dimensions are independent. Return A/B/tie/cannot_judge, quote both reports. Prefer justified differences, traceability, useful scientific relations and bounded uncertainty, not length/confidence. Ignore system names. Missing technical outputs are not ties.',
'tone': 'For each reviewer section independently describe rhetorical tone and substantive scientific stance; politeness or general praise does not resolve a scientific concern.',
'review_dynamics': 'Link concern history by same reviewer, object and scope across rounds. Record author reply separately. Explicitly resolved requires a later same-reviewer statement addressing this concern. Silence, author self-claims and general politeness never count as resolution. Preserve all quotations and unresolved/no-followup cases.',
'controls': 'Construct at most ONE matched original/altered pair per category using supplied actual report units: source_mismatch (change source only), firstness_overreach (change bounded priority to universal firstness), scope_deletion (DELETE substantive necessary qualification, do not just prepend universal words). Keep original statement and source IDs. If no eligible real original exists omit that category. No fabrication of originals.',
'recheck': 'Independently judge statement against supplied sources using supported/partly_supported/not_verifiable/contradicted, scope and errors. No earlier labels. Retain uncertainty and exact evidence.',
'adjudicate': 'Explain disagreement between two independent evaluations using original task materials and source evidence. This is explanation only, not replacement of main results. Explicitly state unresolved if evidence cannot settle the category difference.',
}

PROMPTS['support'] += (' A substantive scope limitation needs verification too. A graph_observation can support '
    'actual topology or recorded graph metadata, but its generated claim_text/interpretation is NOT independent '
    'evidence for manuscript results, causal claims or historical differences. Use original source_sentence_texts '
    'or original manuscript/historical passages for those claims. A coverage record only supports a limitation '
    'about the selected materials, never absence in the whole manuscript or literature.')
PROMPTS['clusters'] = ('Group anonymous substantive nonparaphrase assertions by the SAME scientific information '
    'at matching scope, regardless of whether their wording or support judgments differ. Every supplied unit_key '
    'belongs exactly once. Preserve exact unit_keys. Distinct scientific increments must remain separate; mere '
    'topical overlap is not identity. Classify historical_increment/cross_work_relation/scope_correction/cross_contribution.')
