from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from experiments.kg_perturbation_fig4.main_fig4 import (  # noqa: E402
    build_fig4_candidate_screen,
    build_fig4_external_validation_target_audit,
    build_fig4_external_validation_gates,
    build_fig4_blinded_labeling_package,
    build_fig4_blinded_labeling_completion_audit,
    build_fig4_blinded_external_validation_gates,
    build_fig4_blinded_external_validation_metrics,
    merge_fig4_labeler_blinded_label_returns,
    agent_cache_needs_refresh_for_nature,
    build_fig4_external_validation_replacement_manifest,
    build_fig4_global_score_coverage_audit,
    build_fig4_global_validation_candidate_packet,
    collect_cached_scored_candidate_pool,
    enforce_fig4_nature_agent_outputs,
    extract_row_keywords,
    fig4_agent_runtime_provenance,
    enforce_fixed_sample_contract,
    heuristic_innovation_label_payload,
    load_fig4_cached_external_retrieval,
    parse_peer_review_markdown,
    prepare_peer_review_text_for_judge,
    sample_manifest,
    stratified_sample_scored_pool,
    validate_fig4_agent_outputs_for_nature_ready,
    semantic_covered_aspect_count,
)


class Fig4ExternalValidationTests(unittest.TestCase):
    def test_fixed_sample_contract_requires_exact_evaluable_count(self) -> None:
        sample = [{"paper_id": f"p{i}", "screen_pass": True} for i in range(49)]
        with self.assertRaises(RuntimeError):
            enforce_fixed_sample_contract(sample, requested_sample_size=50)

        ok = enforce_fixed_sample_contract(
            [{"paper_id": f"p{i}", "screen_pass": True} for i in range(50)],
            requested_sample_size=50,
        )
        self.assertEqual(50, ok["evaluable_case_count"])

    def test_external_validation_gates_block_lightweight_or_zero_coverage(self) -> None:
        manifest = pd.DataFrame({"paper_id": [f"p{i}" for i in range(50)]})
        metrics = pd.DataFrame(
            {
                "paper_id": [f"p{i}" for i in range(50)],
                "embedding_backend": ["lexical_fallback"] * 50,
                "retrieval_source": ["local_fig4_manifest"] * 50,
                "soft_claim_recall": [0.0] * 50,
                "claim_evidence_coverage": [0.0] * 50,
                "covered_peer_aspects": [0.0] * 50,
                "missing_peer_point_rate": [1.0] * 50,
                "fig3_sw": [1.0] * 50,
                "peer_novelty": list(range(50)),
                "peer_significance": list(range(50)),
            }
        )

        gates = build_fig4_external_validation_gates(metrics, manifest, requested_sample_size=50)

        self.assertFalse(gates["overall_pass"])
        self.assertEqual(0, gates["checks"]["embedding_backend_not_lexical_fallback"])
        self.assertEqual(0, gates["checks"]["retrieval_not_local_manifest"])
        self.assertEqual(0, gates["checks"]["soft_claim_recall_nonzero"])
        self.assertIn("peer-review equivalence", gates["forbidden_claim"])
        self.assertIn("reviewer replacement", gates["forbidden_claim"])
        self.assertNotIn("human-like", gates["forbidden_claim"].lower())

    def test_nature_agent_output_audit_rejects_reused_lightweight_fallbacks(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            rows = [
                {
                    "paper_id": "p1",
                    "success": True,
                    "innovation_evaluation": "Full ASPR review.",
                    "agent_runtime_seconds": 12.0,
                    "retrieval_source": "openalex",
                    "agent_model": "qwen3:8b",
                    "agent_base_url": "http://localhost:11434/v1",
                    "agent_max_iterations": 0,
                    "agent_candidates": 1,
                    "agent_beam_width": 1,
                    "agent_max_tokens": 900,
                    "agent_prompt_prefix": "/no_think",
                    "agent_search_mode": "single_pass_lats_initial",
                },
                {
                    "paper_id": "p2",
                    "success": False,
                    "innovation_evaluation": "Fallback review.",
                    "failure_reason": "lats_failed_lightweight_fallback:No module named 'langgraph'",
                    "evaluation_log": ["Generated by deterministic Fig.4 lightweight innovation agent fallback."],
                    "agent_runtime_seconds": 2.0,
                    "retrieval_source": "openalex",
                },
            ]
            (output_dir / "fig4_agent_outputs.jsonl").write_text(
                "\n".join(json.dumps(row) for row in rows) + "\n",
                encoding="utf-8",
            )

            audit = validate_fig4_agent_outputs_for_nature_ready(output_dir, expected_case_count=2)

            self.assertFalse(audit["overall_pass"])
            self.assertEqual(2, audit["observed_case_count"])
            self.assertEqual(1, audit["successful_nonfallback_count"])
            self.assertEqual(1, audit["fallback_or_failed_count"])
            self.assertIn("p2", audit["fallback_or_failed_case_ids"])
            with self.assertRaises(RuntimeError):
                enforce_fig4_nature_agent_outputs(output_dir, expected_case_count=2)

    def test_cached_external_retrieval_reuses_only_audited_openalex_or_s2_sources(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            cache_dir = Path(tmp)
            (cache_dir / "retrieved_papers.json").write_text(
                json.dumps({"paper_id": "p1", "retrieved_papers": [{"title": "Prior", "abstract": "A"}]}),
                encoding="utf-8",
            )
            (cache_dir / "retrieval_audit.json").write_text(
                json.dumps(
                    {
                        "retrieval_source": "openalex",
                        "s2_key_status": "openalex_key_ok",
                        "query_terms": ["prior"],
                        "query_audits": [{"query": "prior"}],
                        "ranker_status": {"recall_backend": "bge_m3"},
                        "excluded_candidates": [{"title": "Future", "reasons": ["post_publication_year"]}],
                    }
                ),
                encoding="utf-8",
            )

            cached = load_fig4_cached_external_retrieval(cache_dir)
            self.assertTrue(cached["cache_hit"])
            self.assertEqual("openalex", cached["retrieval_source"])
            self.assertEqual(1, len(cached["papers"]))

            (cache_dir / "retrieval_audit.json").write_text(
                json.dumps({"retrieval_source": "local_fig4_manifest"}),
                encoding="utf-8",
            )
            local = load_fig4_cached_external_retrieval(cache_dir)
            self.assertFalse(local["cache_hit"])
            self.assertEqual("cached_retrieval_not_external", local["failure_reason"])

    def test_agent_cache_refresh_decision_targets_only_invalid_or_fallback_outputs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            ok_dir = root / "ok"
            bad_dir = root / "bad"
            ok_dir.mkdir()
            bad_dir.mkdir()
            (ok_dir / "agent_eval.json").write_text(
                json.dumps(
                    {
                        "paper_id": "p1",
                        "success": True,
                        "innovation_evaluation": "Observed review.",
                        "agent_runtime_seconds": 10,
                        "agent_model": "qwen3:8b",
                        "agent_base_url": "http://localhost:11434/v1",
                        "agent_max_iterations": 0,
                        "agent_candidates": 1,
                        "agent_beam_width": 1,
                        "agent_max_tokens": 900,
                        "agent_prompt_prefix": "/no_think",
                        "agent_search_mode": "single_pass_lats_initial",
                    }
                ),
                encoding="utf-8",
            )
            (bad_dir / "agent_eval.json").write_text(
                json.dumps(
                    {
                        "paper_id": "p2",
                        "success": False,
                        "innovation_evaluation": "Fallback review.",
                        "failure_reason": "lats_failed_lightweight_fallback:No module named 'langgraph'",
                        "evaluation_log": ["Generated by deterministic Fig.4 lightweight innovation agent fallback."],
                        "agent_runtime_seconds": 2,
                    }
                ),
                encoding="utf-8",
            )

            self.assertFalse(agent_cache_needs_refresh_for_nature(ok_dir))
            self.assertTrue(agent_cache_needs_refresh_for_nature(bad_dir))
            self.assertTrue(agent_cache_needs_refresh_for_nature(root / "missing"))

            legacy_dir = root / "legacy"
            legacy_dir.mkdir()
            (legacy_dir / "agent_eval.json").write_text(
                json.dumps(
                    {
                        "paper_id": "p3",
                        "success": True,
                        "innovation_evaluation": "Observed review without reproducibility metadata.",
                        "agent_runtime_seconds": 10,
                    }
                ),
                encoding="utf-8",
            )
            self.assertTrue(agent_cache_needs_refresh_for_nature(legacy_dir))

    def test_agent_runtime_provenance_records_reproducible_lats_controls(self) -> None:
        old_env = {
            "ASPR_LATS_LLM_MODEL": None,
            "FIG4_AGENT_MAX_ITERATIONS": None,
            "ASPR_LATS_CANDIDATES": None,
            "ASPR_LATS_BEAM_WIDTH": None,
            "ASPR_LATS_MAX_TOKENS": None,
            "ASPR_LATS_PROMPT_PREFIX": None,
            "ASPR_LATS_SINGLE_PASS": None,
        }
        import os

        for key in old_env:
            old_env[key] = os.environ.get(key)
        try:
            os.environ["ASPR_LATS_LLM_MODEL"] = "qwen3:8b"
            os.environ["FIG4_AGENT_MAX_ITERATIONS"] = "0"
            os.environ["ASPR_LATS_CANDIDATES"] = "1"
            os.environ["ASPR_LATS_BEAM_WIDTH"] = "1"
            os.environ["ASPR_LATS_MAX_TOKENS"] = "900"
            os.environ["ASPR_LATS_PROMPT_PREFIX"] = "/no_think"
            os.environ["ASPR_LATS_SINGLE_PASS"] = "1"

            provenance = fig4_agent_runtime_provenance()
        finally:
            for key, value in old_env.items():
                if value is None:
                    os.environ.pop(key, None)
                else:
                    os.environ[key] = value

        self.assertEqual("qwen3:8b", provenance["agent_model"])
        self.assertEqual(0, provenance["agent_max_iterations"])
        self.assertEqual(1, provenance["agent_candidates"])
        self.assertEqual(1, provenance["agent_beam_width"])
        self.assertEqual(900, provenance["agent_max_tokens"])
        self.assertEqual("/no_think", provenance["agent_prompt_prefix"])
        self.assertEqual("single_pass_lats_initial", provenance["agent_search_mode"])

    def test_lats_zero_max_iterations_stops_after_initial_node(self) -> None:
        from aspr.lats import should_loop

        class Root:
            height = 1
            is_solved = False

        self.assertEqual("__end__", should_loop({"root": Root(), "max_iterations": 0}))

    def test_external_validation_gates_accept_real_backend_and_positive_alignment(self) -> None:
        manifest = pd.DataFrame({"paper_id": [f"p{i}" for i in range(50)]})
        values = [float(i) for i in range(50)]
        metrics = pd.DataFrame(
            {
                "paper_id": [f"p{i}" for i in range(50)],
                "embedding_backend": ["bge-m3"] * 50,
                "retrieval_source": ["semantic_scholar"] * 50,
                "soft_claim_recall": [0.2] * 50,
                "claim_evidence_coverage": [0.1] * 50,
                "covered_peer_aspects": [2.0] * 50,
                "missing_peer_point_rate": [0.8] * 50,
                "fig3_sw": values,
                "fig3_sw_tier": ["low"] * 17 + ["middle"] * 16 + ["high"] * 17,
                "peer_novelty": values,
                "peer_significance": values,
            }
        )

        gates = build_fig4_external_validation_gates(metrics, manifest, requested_sample_size=50)

        self.assertTrue(gates["overall_pass"])
        self.assertEqual(1, gates["checks"]["fig3_peer_novelty_positive"])
        self.assertEqual(1, gates["checks"]["fig3_peer_significance_positive"])
        self.assertEqual(1, gates["checks"]["peer_novelty_variance_present"])
        self.assertEqual(1, gates["checks"]["fig3_reference_tier_range_present"])

    def test_external_validation_gates_block_constant_peer_labels_and_single_fig3_tier(self) -> None:
        manifest = pd.DataFrame({"paper_id": [f"p{i}" for i in range(50)]})
        metrics = pd.DataFrame(
            {
                "paper_id": [f"p{i}" for i in range(50)],
                "embedding_backend": ["bge-m3"] * 50,
                "retrieval_source": ["openalex"] * 50,
                "soft_claim_recall": [0.2] * 50,
                "claim_evidence_coverage": [0.2] * 50,
                "covered_peer_aspects": [2.0] * 50,
                "missing_peer_point_rate": [0.8] * 50,
                "fig3_sw": [1.0] * 50,
                "fig3_sw_tier": ["high"] * 50,
                "peer_novelty": [3.0] * 50,
                "peer_significance": [3.0] * 50,
            }
        )

        gates = build_fig4_external_validation_gates(metrics, manifest, requested_sample_size=50)

        self.assertFalse(gates["overall_pass"])
        self.assertEqual(0, gates["checks"]["peer_novelty_variance_present"])
        self.assertEqual(0, gates["checks"]["peer_significance_variance_present"])
        self.assertEqual(0, gates["checks"]["fig3_reference_tier_range_present"])

    def test_fig4_external_validation_target_audit_reports_label_and_score_range(self) -> None:
        metrics = pd.DataFrame(
            {
                "paper_id": [f"p{i}" for i in range(6)],
                "fig3_sw": [1.0, 1.1, 1.2, 2.0, 2.1, 2.2],
                "fig3_sw_tier": ["low", "low", "middle", "middle", "high", "high"],
                "peer_novelty": [2, 2, 3, 3, 4, 4],
                "peer_significance": [2, 3, 3, 4, 4, 5],
            }
        )

        audit = build_fig4_external_validation_target_audit(metrics)

        self.assertEqual(6, audit["n_cases"])
        self.assertEqual(3, audit["peer_novelty_unique"])
        self.assertEqual(4, audit["peer_significance_unique"])
        self.assertEqual(3, audit["fig3_reference_tier_unique"])
        self.assertEqual(1, audit["external_validation_target_range_ready"])

    def test_target_audit_rejects_batch_ladder_when_global_reference_tier_is_high_only(self) -> None:
        metrics = pd.DataFrame(
            {
                "paper_id": [f"p{i}" for i in range(9)],
                "fig3_sw": [1.0, 1.1, 1.2, 2.0, 2.1, 2.2, 2.8, 2.9, 3.0],
                "fig3_sw_tier": ["high"] * 9,
                "fig3_sw_percentile": [0.94, 0.95, 0.96, 0.97, 0.98, 0.985, 0.99, 0.995, 0.999],
                "fig4_sw_ladder_tier": ["low"] * 3 + ["middle"] * 3 + ["high"] * 3,
                "peer_novelty": [2, 2, 3, 3, 4, 4, 5, 5, 5],
                "peer_significance": [2, 3, 3, 4, 4, 5, 5, 5, 5],
            }
        )

        audit = build_fig4_external_validation_target_audit(metrics)

        self.assertEqual(1, audit["fig3_reference_tier_unique"])
        self.assertEqual(3, audit["fig4_batch_ladder_tier_unique"])
        self.assertEqual(0, audit["fig3_score_range_ready"])
        self.assertEqual(0, audit["external_validation_target_range_ready"])

    def test_target_audit_accepts_global_percentile_range_without_reference_tiers(self) -> None:
        metrics = pd.DataFrame(
            {
                "paper_id": [f"p{i}" for i in range(6)],
                "fig3_sw": [1.0, 1.1, 1.2, 2.0, 2.1, 2.2],
                "fig3_sw_percentile": [0.12, 0.22, 0.35, 0.72, 0.86, 0.93],
                "peer_novelty": [2, 2, 3, 4, 4, 5],
                "peer_significance": [2, 3, 3, 4, 4, 5],
            }
        )

        audit = build_fig4_external_validation_target_audit(metrics)

        self.assertEqual(1, audit["fig3_reference_percentile_range_ready"])
        self.assertEqual(1, audit["fig3_score_range_ready"])

    def test_heuristic_innovation_labels_score_aspects_with_directional_variance(self) -> None:
        positive = heuristic_innovation_label_payload(
            "Reviewers describe the work as a significant advance with a novel and important contribution."
        )
        negative = heuristic_innovation_label_payload(
            "Reviewers state that the contribution is incremental, not novel, and has limited significance."
        )

        self.assertGreater(
            positive["aspects"]["novelty"]["score_1_5"],
            negative["aspects"]["novelty"]["score_1_5"],
        )
        self.assertGreater(
            positive["aspects"]["significance"]["score_1_5"],
            negative["aspects"]["significance"]["score_1_5"],
        )
        self.assertNotEqual(3, negative["aspects"]["novelty"]["score_1_5"])

    def test_peer_review_parser_removes_inline_author_response_blocks(self) -> None:
        parsed = parse_peer_review_markdown(
            """
            Reviewer #1: Remarks to the Author:

            This is a notable and significant work that I can recommend for publication.

            We thank the reviewers for their thoughtful comments and suggestions. Responses can be found below in blue text.

            ## Reviewer #1
            ## Comments:
            We explain this in the current version of the introduction and further elaborate in the supplement.
            """
        )

        review_text = parsed["peer_review_text"]

        self.assertIn("notable and significant work", review_text)
        self.assertNotIn("We thank the reviewers", review_text)
        self.assertNotIn("Responses can be found", review_text)
        self.assertNotIn("We explain this", review_text)

    def test_prepare_peer_review_text_for_judge_drops_author_voice_sentences(self) -> None:
        prepared = prepare_peer_review_text_for_judge(
            """
            Reviewer #1: The manuscript is novel and important, but the prior-art comparison needs clarification.

            We thank the reviewers for their thoughtful comments and suggestions.
            We explain this in the current version of the introduction and further elaborate in the new supplement.
            The authors have now performed the requested controls.
            """
        )

        self.assertIn("manuscript is novel and important", prepared)
        self.assertNotIn("We thank the reviewers", prepared)
        self.assertNotIn("We explain this", prepared)
        self.assertIn("requested controls", prepared)

    def test_semantic_matches_count_as_covered_peer_aspects(self) -> None:
        rows = [
            {"aspect": "novelty", "relation": "related"},
            {"aspect": "novelty", "relation": "no_match"},
            {"aspect": "significance", "refined_relation": "entailed"},
            {"aspect": "limitations", "relation": "contradicted"},
        ]

        self.assertEqual(2, semantic_covered_aspect_count(rows))

    def test_sample_manifest_ignores_stale_screen_unless_required(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            audit = pd.DataFrame(
                {
                    "paper_id": [f"p{i:03d}" for i in range(60)],
                    "journal_id": ["41551"] * 60,
                    "year": [2023] * 60,
                    "included_in_audit": [True] * 60,
                }
            )
            audit.to_csv(output_dir / "fig4_input_audit.csv", index=False)
            stale_screen = audit.head(47).assign(screen_pass=True)
            stale_screen.to_csv(output_dir / "fig4_peer_review_screen.csv", index=False)

            sampled = sample_manifest(
                output_dir,
                sample_size=50,
                seed=20260617,
                cap_41467=0.5,
                quiet=True,
            )

            self.assertEqual(50, len(sampled))

            with self.assertRaises(RuntimeError):
                sample_manifest(
                    output_dir,
                    sample_size=50,
                    seed=20260617,
                    cap_41467=0.5,
                    quiet=True,
                    require_screen_pass=True,
                )

            preferred = sample_manifest(
                output_dir,
                sample_size=40,
                seed=20260617,
                cap_41467=0.5,
                quiet=True,
                prefer_screen_pass=True,
            )
            self.assertEqual(40, len(preferred))
            self.assertTrue(all(row.get("screen_pass") in {True, "True", "true", "1", 1} for row in preferred))

    def test_sample_manifest_writes_candidate_screen_and_fixed_sample_manifest(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            audit = pd.DataFrame(
                {
                    "paper_id": ["p0", "p1", "p2"],
                    "journal_id": ["41551", "41551", "41551"],
                    "journal": ["Nature Human Behaviour"] * 3,
                    "year": [2023, 2023, 2023],
                    "title": ["Title 0", "Title 1", ""],
                    "abstract": ["Abstract 0", "", "Abstract 2"],
                    "article_word_count": [1200, 1200, 1200],
                    "peer_review_word_count": [900, 0, 900],
                    "peer_review_markdown_path": ["r0.md", "", "r2.md"],
                    "included_in_audit": [True, True, True],
                    "exclusion_reason": ["", "", ""],
                }
            )
            audit.to_csv(output_dir / "fig4_input_audit.csv", index=False)

            screen = build_fig4_candidate_screen(output_dir)
            sampled = sample_manifest(output_dir, sample_size=1, seed=7, cap_41467=0.5, quiet=True)

            self.assertEqual(3, len(screen))
            self.assertTrue((output_dir / "fig4_candidate_screen.csv").exists())
            self.assertTrue((output_dir / "fig4_fixed_sample_manifest.csv").exists())
            self.assertEqual(["p0"], [row["paper_id"] for row in sampled])
            fixed = pd.read_csv(output_dir / "fig4_fixed_sample_manifest.csv")
            self.assertEqual(["p0"], fixed["paper_id"].tolist())
            self.assertIn("has_peer_review_text", screen.columns)
            self.assertEqual([True, False, False], screen["screen_pass"].tolist())

    def test_scored_candidate_pool_supports_stratified_fixed_sample(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            audit = pd.DataFrame(
                {
                    "paper_id": [f"p{i}" for i in range(9)],
                    "journal_id": ["41551"] * 9,
                    "journal": ["Nature Human Behaviour"] * 9,
                    "year": [2023] * 9,
                    "title": [f"Title {i}" for i in range(9)],
                    "abstract": [f"Abstract {i}" for i in range(9)],
                    "article_word_count": [1200] * 9,
                    "peer_review_word_count": [900] * 9,
                    "peer_review_markdown_path": [f"r{i}.md" for i in range(9)],
                    "included_in_audit": [True] * 9,
                    "exclusion_reason": [""] * 9,
                }
            )
            audit.to_csv(output_dir / "fig4_input_audit.csv", index=False)
            for idx in range(9):
                cache_dir = output_dir / "cache" / f"p{idx}"
                cache_dir.mkdir(parents=True)
                tier = "low" if idx < 3 else "middle" if idx < 6 else "high"
                (cache_dir / "fig4_graph_prior.json").write_text(
                    json.dumps(
                        {
                            "paper_id": f"p{idx}",
                            "fig3_sw": float(idx),
                            "fig3_sw_percentile": (idx + 1) / 10.0,
                            "fig3_sw_tier": tier,
                            "fig4_sw_ladder_tier": tier,
                            "graph_metric_valid": True,
                        }
                    ),
                    encoding="utf-8",
                )

            pool = collect_cached_scored_candidate_pool(output_dir)
            sampled = stratified_sample_scored_pool(pool, sample_size=6, seed=3)
            manifest = sample_manifest(
                output_dir,
                sample_size=6,
                seed=3,
                cap_41467=0.5,
                quiet=True,
                prefer_scored_pool=True,
            )

            self.assertEqual(9, len(pool))
            self.assertEqual({"low", "middle", "high"}, set(sampled["fig4_sw_ladder_tier"]))
            self.assertEqual({"fig3_sw_tier"}, set(sampled["sample_tier_column"]))
            self.assertEqual({"low", "middle", "high"}, {row["fig4_sw_ladder_tier"] for row in manifest})
            self.assertEqual({"fig3_sw_tier"}, {row["sample_tier_column"] for row in manifest})
            self.assertTrue((output_dir / "fig4_scored_candidate_pool.csv").exists())
            self.assertTrue((output_dir / "fig4_fixed_sample_manifest.csv").exists())

    def test_scored_pool_does_not_use_batch_ladder_as_global_validation_range(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            audit = pd.DataFrame(
                {
                    "paper_id": [f"p{i}" for i in range(9)],
                    "journal_id": ["41551"] * 9,
                    "journal": ["Nature Human Behaviour"] * 9,
                    "year": [2023] * 9,
                    "title": [f"Title {i}" for i in range(9)],
                    "abstract": [f"Abstract {i}" for i in range(9)],
                    "article_word_count": [1200] * 9,
                    "peer_review_word_count": [900] * 9,
                    "peer_review_markdown_path": [f"r{i}.md" for i in range(9)],
                    "included_in_audit": [True] * 9,
                    "exclusion_reason": [""] * 9,
                }
            )
            audit.to_csv(output_dir / "fig4_input_audit.csv", index=False)
            for idx in range(9):
                cache_dir = output_dir / "cache" / f"p{idx}"
                cache_dir.mkdir(parents=True)
                ladder_tier = "low" if idx < 3 else "middle" if idx < 6 else "high"
                (cache_dir / "fig4_graph_prior.json").write_text(
                    json.dumps(
                        {
                            "paper_id": f"p{idx}",
                            "fig3_sw": float(idx),
                            "fig3_sw_percentile": 0.9 + idx / 100.0,
                            "fig3_sw_tier": "high",
                            "fig4_sw_ladder_tier": ladder_tier,
                            "graph_metric_valid": True,
                        }
                    ),
                    encoding="utf-8",
                )

            pool = collect_cached_scored_candidate_pool(output_dir)
            sampled = stratified_sample_scored_pool(pool, sample_size=6, seed=3)

            self.assertEqual({"fig3_sw_tier"}, set(sampled["sample_tier_column"]))
            self.assertEqual({"high"}, set(sampled["fig3_sw_tier"]))
            self.assertEqual(1, sampled["fig3_sw_tier"].nunique())

    def test_global_score_coverage_audit_reports_missing_low_and_middle_tiers(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            score_table = pd.DataFrame(
                {
                    "paper_id": [f"g{i}" for i in range(100)],
                    "S_w": [float(i) for i in range(100)],
                }
            )
            score_path = output_dir / "fig3_score_table.csv"
            score_table.to_csv(score_path, index=False)
            high_pool = pd.DataFrame(
                {
                    "paper_id": [f"p{i}" for i in range(12)],
                    "fig3_sw_percentile": [0.91 + i * 0.005 for i in range(12)],
                    "screen_pass": [True] * 12,
                }
            )
            high_pool.to_csv(output_dir / "fig4_scored_candidate_pool.csv", index=False)
            high_pool.head(6).to_csv(output_dir / "fig4_fixed_sample_manifest.csv", index=False)

            audit = build_fig4_global_score_coverage_audit(
                output_dir=output_dir,
                fig3_score_table_path=score_path,
                requested_sample_size=6,
                min_cases_per_tier=2,
            )

            by_tier = audit.set_index("global_fig3_tier")
            self.assertEqual(0, int(by_tier.loc["low", "fixed_sample_count"]))
            self.assertEqual(0, int(by_tier.loc["middle", "fixed_sample_count"]))
            self.assertEqual(1, int(by_tier.loc["high", "tier_ready_for_external_validation"]))
            self.assertEqual(0, int(audit["overall_score_coverage_ready"].max()))
            self.assertTrue((output_dir / "fig4_global_score_coverage_audit.csv").exists())

    def test_global_validation_candidate_packet_samples_each_fig3_tier(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            score_table = pd.DataFrame(
                {
                    "paper_id": [f"g{i}" for i in range(30)],
                    "title": [f"Title {i}" for i in range(30)],
                    "domain": ["d1"] * 15 + ["d2"] * 15,
                    "year": [2000 + i % 5 for i in range(30)],
                    "S_w": [float(i) for i in range(30)],
                }
            )
            score_path = output_dir / "fig3_score_table.csv"
            score_table.to_csv(score_path, index=False)

            packet = build_fig4_global_validation_candidate_packet(
                output_dir=output_dir,
                fig3_score_table_path=score_path,
                per_tier=3,
            )

            self.assertEqual({"low", "middle", "high"}, set(packet["global_fig3_tier"]))
            self.assertEqual(3, int(packet.groupby("global_fig3_tier").size().min()))
            self.assertIn("peer_novelty_human_1_5", packet.columns)
            self.assertTrue((output_dir / "fig4_global_validation_candidate_packet.csv").exists())

    def test_global_validation_candidate_packet_preserves_completed_labels_on_rebuild(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            score_table = pd.DataFrame(
                {
                    "paper_id": [f"g{i}" for i in range(30)],
                    "title": [f"Title {i}" for i in range(30)],
                    "domain": ["d1"] * 15 + ["d2"] * 15,
                    "year": [2000 + i % 5 for i in range(30)],
                    "S_w": [float(i) for i in range(30)],
                }
            )
            score_path = output_dir / "fig3_score_table.csv"
            score_table.to_csv(score_path, index=False)

            packet = build_fig4_global_validation_candidate_packet(
                output_dir=output_dir,
                fig3_score_table_path=score_path,
                per_tier=3,
            )
            edited = packet.copy()
            edited.loc[0, "peer_novelty_human_1_5"] = "5"
            edited.loc[0, "peer_significance_human_1_5"] = "4"
            edited.loc[0, "label_source"] = "external_peer_label"
            edited.loc[0, "labeler_id"] = "peer_1"
            edited.loc[0, "label_notes"] = "keep this label"
            edited.to_csv(output_dir / "fig4_global_validation_candidate_packet.csv", index=False)

            rebuilt = build_fig4_global_validation_candidate_packet(
                output_dir=output_dir,
                fig3_score_table_path=score_path,
                per_tier=3,
            )

        preserved = rebuilt[rebuilt["paper_id"].eq(str(packet.loc[0, "paper_id"]))].iloc[0]
        self.assertEqual("5", str(preserved["peer_novelty_human_1_5"]))
        self.assertEqual("4", str(preserved["peer_significance_human_1_5"]))
        self.assertEqual("external_peer_label", preserved["label_source"])
        self.assertEqual("peer_1", preserved["labeler_id"])
        self.assertEqual("keep this label", preserved["label_notes"])

    def test_blinded_labeling_package_hides_fig3_score_and_balances_tiers(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet = pd.DataFrame(
                {
                    "paper_id": [f"d::https://openalex.org/W{i}" for i in range(18)],
                    "title": [f"Title {i}" for i in range(18)],
                    "domain": ["d"] * 18,
                    "year": [2010 + i for i in range(18)],
                    "primary_field": ["field"] * 18,
                    "fig3_score_for_validation": [float(i) for i in range(18)],
                    "fig3_global_percentile": [(i + 1) / 18 for i in range(18)],
                    "global_fig3_tier": ["low"] * 6 + ["middle"] * 6 + ["high"] * 6,
                }
            )

            blinded, answer_key, protocol = build_fig4_blinded_labeling_package(
                output_dir=output_dir,
                candidate_packet=packet,
                primary_per_tier=2,
                reserve_per_tier=1,
                seed=7,
            )
            self.assertTrue((output_dir / "fig4_blinded_labeling_protocol.md").exists())

        self.assertEqual(9, len(blinded))
        self.assertEqual(9, len(answer_key))
        self.assertEqual(6, int(blinded["assignment_role"].eq("primary_validation_labeling_sample").sum()))
        self.assertFalse({"fig3_score_for_validation", "fig3_global_percentile", "global_fig3_tier"}.intersection(blinded.columns))
        self.assertEqual({"low", "middle", "high"}, set(answer_key["global_fig3_tier"]))
        self.assertEqual(3, int(answer_key.groupby("global_fig3_tier").size().min()))
        self.assertEqual("ready_for_blinded_human_or_peer_labeling", protocol["status"])

    def test_blinded_labeling_ids_do_not_encode_tier_blocks(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet = pd.DataFrame(
                {
                    "paper_id": [f"d::https://openalex.org/W{i}" for i in range(18)],
                    "title": [f"Title {i}" for i in range(18)],
                    "domain": ["d"] * 18,
                    "year": [2010 + i for i in range(18)],
                    "primary_field": ["field"] * 18,
                    "fig3_score_for_validation": [float(i) for i in range(18)],
                    "fig3_global_percentile": [(i + 1) / 18 for i in range(18)],
                    "global_fig3_tier": ["low"] * 6 + ["middle"] * 6 + ["high"] * 6,
                }
            )

            _blinded, answer_key, protocol = build_fig4_blinded_labeling_package(
                output_dir=output_dir,
                candidate_packet=packet,
                primary_per_tier=2,
                reserve_per_tier=1,
                seed=7,
            )

        ordered_tiers = answer_key.sort_values("blinded_case_id")["global_fig3_tier"].astype(str).tolist()
        tier_rank = {"low": 0, "middle": 1, "high": 2}
        self.assertNotEqual(sorted(ordered_tiers, key=tier_rank.get), ordered_tiers)
        self.assertNotEqual(["low"] * 3 + ["middle"] * 3 + ["high"] * 3, ordered_tiers)
        self.assertIn("randomized across Fig.3 tiers", protocol["blinding_rule"])

    def test_blinded_labeling_package_writes_completed_label_template_for_primary_cases(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet = pd.DataFrame(
                {
                    "paper_id": [f"d::https://openalex.org/W{i}" for i in range(18)],
                    "title": [f"Title {i}" for i in range(18)],
                    "domain": ["d"] * 18,
                    "year": [2010 + i for i in range(18)],
                    "primary_field": ["field"] * 18,
                    "fig3_score_for_validation": [float(i) for i in range(18)],
                    "fig3_global_percentile": [(i + 1) / 18 for i in range(18)],
                    "global_fig3_tier": ["low"] * 6 + ["middle"] * 6 + ["high"] * 6,
                }
            )

            _blinded, _answer_key, protocol = build_fig4_blinded_labeling_package(
                output_dir=output_dir,
                candidate_packet=packet,
                primary_per_tier=2,
                reserve_per_tier=1,
                seed=7,
            )
            template_path = output_dir / "fig4_completed_blinded_labels_template.csv"
            template = pd.read_csv(template_path)

        self.assertEqual(6, len(template))
        self.assertEqual({"primary_validation_labeling_sample"}, set(template["assignment_role"].astype(str)))
        self.assertFalse({"paper_id", "fig3_score_for_validation", "fig3_global_percentile", "global_fig3_tier"}.intersection(template.columns))
        self.assertTrue(
            {
                "blinded_case_id",
                "assignment_role",
                "title",
                "source_openalex_url",
                "label_novelty_1_5",
                "label_significance_1_5",
                "label_prior_art_1_5",
                "label_confidence_1_5",
                "label_source",
                "labeler_id",
                "label_notes",
            }.issubset(template.columns)
        )
        self.assertIn("fig4_completed_blinded_labels_template.csv", protocol["completed_label_template_path"])

    def test_blinded_labeling_completion_audit_requires_valid_labels_per_tier(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet = pd.DataFrame(
                {
                    "blinded_case_id": [f"F4LV-{idx:04d}" for idx in range(1, 7)],
                    "assignment_role": ["primary_validation_labeling_sample"] * 6,
                    "label_novelty_1_5": [4, 5, 3, 4, "", ""],
                    "label_significance_1_5": [4, 5, 3, 4, "", ""],
                    "label_source": ["human"] * 4 + ["", ""],
                }
            )
            key = pd.DataFrame(
                {
                    "blinded_case_id": [f"F4LV-{idx:04d}" for idx in range(1, 7)],
                    "global_fig3_tier": ["low", "low", "middle", "middle", "high", "high"],
                }
            )
            packet.to_csv(output_dir / "fig4_blinded_labeling_packet.csv", index=False)
            key.to_csv(output_dir / "fig4_blinded_labeling_answer_key.csv", index=False)

            audit = build_fig4_blinded_labeling_completion_audit(output_dir, min_primary_per_tier=2)

        by_tier = audit.set_index("global_fig3_tier")
        self.assertEqual(1, int(by_tier.loc["low", "tier_label_ready"]))
        self.assertEqual(1, int(by_tier.loc["middle", "tier_label_ready"]))
        self.assertEqual(0, int(by_tier.loc["high", "tier_label_ready"]))
        self.assertEqual(0, int(audit["overall_blinded_labeling_ready"].max()))

    def test_external_validation_replacement_manifest_reports_missing_primary_labels(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet_rows = []
            key_rows = []
            idx = 1
            for tier in ["low", "middle", "high"]:
                for _ in range(2):
                    blinded_id = f"F4LV-{idx:04d}"
                    idx += 1
                    packet_rows.append(
                        {
                            "blinded_case_id": blinded_id,
                            "assignment_role": "primary_validation_labeling_sample",
                            "title": f"{tier} title",
                            "label_novelty_1_5": "",
                            "label_significance_1_5": "",
                            "label_prior_art_1_5": "",
                            "label_confidence_1_5": "",
                            "label_source": "",
                            "labeler_id": "",
                        }
                    )
                    key_rows.append(
                        {
                            "blinded_case_id": blinded_id,
                            "paper_id": f"{tier}-{idx}",
                            "global_fig3_tier": tier,
                            "fig3_score_for_validation": float(idx),
                            "fig3_global_percentile": 0.2 if tier == "low" else 0.5 if tier == "middle" else 0.8,
                            "assignment_role": "primary_validation_labeling_sample",
                        }
                    )
            pd.DataFrame(packet_rows).to_csv(output_dir / "fig4_blinded_labeling_packet.csv", index=False)
            pd.DataFrame(key_rows).to_csv(output_dir / "fig4_blinded_labeling_answer_key.csv", index=False)

            manifest = build_fig4_external_validation_replacement_manifest(output_dir, min_primary_per_tier=2)
            summary = pd.read_csv(output_dir / "fig4_external_validation_replacement_summary.csv")

        self.assertEqual(6, len(manifest))
        self.assertEqual({"low", "middle", "high"}, set(manifest["global_fig3_tier"]))
        self.assertEqual(0, int(manifest["replacement_ready"].max()))
        self.assertIn("label_novelty_1_5", manifest["missing_label_fields"].iloc[0])
        self.assertEqual(0, int(summary["overall_replacement_ready"].max()))

    def test_external_validation_replacement_manifest_passes_complete_primary_labels(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet_rows = []
            key_rows = []
            idx = 1
            for tier in ["low", "middle", "high"]:
                for _ in range(2):
                    blinded_id = f"F4LV-{idx:04d}"
                    idx += 1
                    packet_rows.append(
                        {
                            "blinded_case_id": blinded_id,
                            "assignment_role": "primary_validation_labeling_sample",
                            "title": f"{tier} title",
                            "label_novelty_1_5": 4,
                            "label_significance_1_5": 4,
                            "label_prior_art_1_5": 3,
                            "label_confidence_1_5": 5,
                            "label_source": "blinded_human_label",
                            "labeler_id": "r1",
                        }
                    )
                    key_rows.append(
                        {
                            "blinded_case_id": blinded_id,
                            "paper_id": f"{tier}-{idx}",
                            "global_fig3_tier": tier,
                            "fig3_score_for_validation": float(idx),
                            "fig3_global_percentile": 0.2 if tier == "low" else 0.5 if tier == "middle" else 0.8,
                            "assignment_role": "primary_validation_labeling_sample",
                        }
                    )
            pd.DataFrame(packet_rows).to_csv(output_dir / "fig4_blinded_labeling_packet.csv", index=False)
            pd.DataFrame(key_rows).to_csv(output_dir / "fig4_blinded_labeling_answer_key.csv", index=False)

            manifest = build_fig4_external_validation_replacement_manifest(output_dir, min_primary_per_tier=2)
            summary = pd.read_csv(output_dir / "fig4_external_validation_replacement_summary.csv")

        self.assertEqual(1, int(manifest["replacement_ready"].min()))
        self.assertEqual(1, int(summary["overall_replacement_ready"].max()))

    def test_blinded_external_validation_passes_with_complete_positive_labels(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet_rows = []
            key_rows = []
            tiers = [("low", 0.10, 2), ("middle", 0.65, 3), ("high", 0.92, 4)]
            case_idx = 1
            for tier, percentile_start, label_start in tiers:
                for offset in range(10):
                    blind_id = f"F4LV-{case_idx:04d}"
                    packet_rows.append(
                        {
                            "blinded_case_id": blind_id,
                            "assignment_role": "primary_validation_labeling_sample",
                            "title": f"Title {case_idx}",
                            "label_novelty_1_5": label_start + (offset % 2),
                            "label_significance_1_5": label_start + (offset % 2),
                            "label_prior_art_1_5": label_start,
                            "label_confidence_1_5": 4,
                            "label_source": "human_blinded",
                            "labeler_id": f"r{offset % 3}",
                        }
                    )
                    key_rows.append(
                        {
                            "blinded_case_id": blind_id,
                            "paper_id": f"p{case_idx}",
                            "global_fig3_tier": tier,
                            "fig3_score_for_validation": float(case_idx),
                            "fig3_global_percentile": percentile_start + offset * 0.002,
                            "assignment_role": "primary_validation_labeling_sample",
                        }
                    )
                    case_idx += 1
            pd.DataFrame(packet_rows).to_csv(output_dir / "fig4_blinded_labeling_packet.csv", index=False)
            pd.DataFrame(key_rows).to_csv(output_dir / "fig4_blinded_labeling_answer_key.csv", index=False)

            metrics = build_fig4_blinded_external_validation_metrics(output_dir)
            gates = build_fig4_blinded_external_validation_gates(output_dir, min_primary_per_tier=10)

        self.assertEqual(30, len(metrics))
        self.assertTrue(gates["overall_pass"], gates)
        self.assertEqual(1, gates["checks"]["blinded_labeling_complete"])
        self.assertEqual(1, gates["checks"]["fig3_peer_novelty_positive"])
        self.assertEqual(1, gates["checks"]["fig3_peer_significance_positive"])
        self.assertEqual(1, gates["checks"]["fig3_peer_novelty_ci_positive"])
        self.assertEqual(1, gates["checks"]["fig3_peer_significance_ci_positive"])
        self.assertGreater(gates["bootstrap_spearman"]["peer_novelty"]["ci_low"], 0.0)
        self.assertGreater(gates["bootstrap_spearman"]["peer_significance"]["ci_low"], 0.0)

    def test_blinded_external_validation_blocks_when_bootstrap_ci_crosses_zero(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet_rows = []
            key_rows = []
            tiers = [("low", 0.10), ("middle", 0.65), ("high", 0.92)]
            noisy_labels = [1, 5, 1, 5, 2, 4, 2, 4, 3, 3]
            case_idx = 1
            for tier_index, (tier, percentile_start) in enumerate(tiers):
                for offset in range(10):
                    blind_id = f"F4LV-{case_idx:04d}"
                    weak_label = noisy_labels[offset] if tier_index == 1 else 3
                    packet_rows.append(
                        {
                            "blinded_case_id": blind_id,
                            "assignment_role": "primary_validation_labeling_sample",
                            "title": f"Title {case_idx}",
                            "label_novelty_1_5": weak_label,
                            "label_significance_1_5": weak_label,
                            "label_source": "human_blinded",
                            "labeler_id": f"r{offset % 3}",
                        }
                    )
                    key_rows.append(
                        {
                            "blinded_case_id": blind_id,
                            "paper_id": f"p{case_idx}",
                            "global_fig3_tier": tier,
                            "fig3_score_for_validation": float(case_idx),
                            "fig3_global_percentile": percentile_start + offset * 0.002,
                            "assignment_role": "primary_validation_labeling_sample",
                        }
                    )
                    case_idx += 1
            pd.DataFrame(packet_rows).to_csv(output_dir / "fig4_blinded_labeling_packet.csv", index=False)
            pd.DataFrame(key_rows).to_csv(output_dir / "fig4_blinded_labeling_answer_key.csv", index=False)

            gates = build_fig4_blinded_external_validation_gates(output_dir, min_primary_per_tier=10)

        self.assertFalse(gates["overall_pass"], gates)
        self.assertEqual(0, gates["checks"]["fig3_peer_novelty_ci_positive"])
        self.assertEqual(0, gates["checks"]["fig3_peer_significance_ci_positive"])
        self.assertLessEqual(gates["bootstrap_spearman"]["peer_novelty"]["ci_low"], 0.0)

    def test_blinded_external_validation_blocks_incomplete_or_nonpositive_labels(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet = pd.DataFrame(
                {
                    "blinded_case_id": [f"F4LV-{idx:04d}" for idx in range(1, 7)],
                    "assignment_role": ["primary_validation_labeling_sample"] * 6,
                    "label_novelty_1_5": [5, 5, 4, 4, "", ""],
                    "label_significance_1_5": [5, 5, 4, 4, "", ""],
                    "label_source": ["human_blinded"] * 4 + ["", ""],
                }
            )
            key = pd.DataFrame(
                {
                    "blinded_case_id": [f"F4LV-{idx:04d}" for idx in range(1, 7)],
                    "paper_id": [f"p{idx}" for idx in range(1, 7)],
                    "global_fig3_tier": ["low", "low", "middle", "middle", "high", "high"],
                    "fig3_score_for_validation": [1, 2, 3, 4, 5, 6],
                    "fig3_global_percentile": [0.1, 0.2, 0.6, 0.7, 0.9, 0.95],
                    "assignment_role": ["primary_validation_labeling_sample"] * 6,
                }
            )
            packet.to_csv(output_dir / "fig4_blinded_labeling_packet.csv", index=False)
            key.to_csv(output_dir / "fig4_blinded_labeling_answer_key.csv", index=False)

            gates = build_fig4_blinded_external_validation_gates(output_dir, min_primary_per_tier=2)

        self.assertFalse(gates["overall_pass"])
        self.assertEqual(0, gates["checks"]["blinded_labeling_complete"])
        self.assertEqual(0, gates["checks"]["fig3_peer_novelty_positive"])

    def test_blinded_labeling_package_preserves_existing_completed_labels(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet = pd.DataFrame(
                {
                    "paper_id": [f"d::https://openalex.org/W{i}" for i in range(18)],
                    "title": [f"Title {i}" for i in range(18)],
                    "domain": ["d"] * 18,
                    "year": [2010 + i for i in range(18)],
                    "primary_field": ["field"] * 18,
                    "fig3_score_for_validation": [float(i) for i in range(18)],
                    "fig3_global_percentile": [(i + 1) / 18 for i in range(18)],
                    "global_fig3_tier": ["low"] * 6 + ["middle"] * 6 + ["high"] * 6,
                }
            )
            blinded, answer_key, _protocol = build_fig4_blinded_labeling_package(
                output_dir=output_dir,
                candidate_packet=packet,
                primary_per_tier=2,
                reserve_per_tier=1,
                seed=7,
            )
            edited = blinded.copy()
            first_primary = edited["assignment_role"].eq("primary_validation_labeling_sample")
            edited.loc[first_primary, "label_novelty_1_5"] = "4"
            edited.loc[first_primary, "label_significance_1_5"] = "5"
            edited.loc[first_primary, "label_source"] = "human_blinded"
            edited.loc[first_primary, "labeler_id"] = "rater_1"
            edited.to_csv(output_dir / "fig4_blinded_labeling_packet.csv", index=False)
            answer_key.to_csv(output_dir / "fig4_blinded_labeling_answer_key.csv", index=False)

            rebuilt, _rebuilt_key, _rebuilt_protocol = build_fig4_blinded_labeling_package(
                output_dir=output_dir,
                candidate_packet=packet,
                primary_per_tier=2,
                reserve_per_tier=1,
                seed=7,
            )

        rebuilt_primary = rebuilt[rebuilt["assignment_role"].eq("primary_validation_labeling_sample")]
        self.assertEqual({4}, set(pd.to_numeric(rebuilt_primary["label_novelty_1_5"], errors="coerce").dropna().astype(int)))
        self.assertEqual({5}, set(pd.to_numeric(rebuilt_primary["label_significance_1_5"], errors="coerce").dropna().astype(int)))
        self.assertEqual({"human_blinded"}, set(rebuilt_primary["label_source"].astype(str)))
        self.assertEqual({"rater_1"}, set(rebuilt_primary["labeler_id"].astype(str)))

    def test_blinded_labeling_package_imports_completed_label_sidecar(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet = pd.DataFrame(
                {
                    "paper_id": [f"d::https://openalex.org/W{i}" for i in range(18)],
                    "title": [f"Title {i}" for i in range(18)],
                    "domain": ["d"] * 18,
                    "year": [2010 + i for i in range(18)],
                    "primary_field": ["field"] * 18,
                    "fig3_score_for_validation": [float(i) for i in range(18)],
                    "fig3_global_percentile": [(i + 1) / 18 for i in range(18)],
                    "global_fig3_tier": ["low"] * 6 + ["middle"] * 6 + ["high"] * 6,
                }
            )
            first_packet, answer_key, _protocol = build_fig4_blinded_labeling_package(
                output_dir=output_dir,
                candidate_packet=packet,
                primary_per_tier=2,
                reserve_per_tier=1,
                seed=7,
            )
            primary_ids = first_packet[first_packet["assignment_role"].eq("primary_validation_labeling_sample")]["blinded_case_id"]
            pd.DataFrame(
                {
                    "blinded_case_id": list(primary_ids),
                    "label_novelty_1_5": [4] * len(primary_ids),
                    "label_significance_1_5": [5] * len(primary_ids),
                    "label_prior_art_1_5": [3] * len(primary_ids),
                    "label_confidence_1_5": [4] * len(primary_ids),
                    "label_source": ["completed_blinded_label_file"] * len(primary_ids),
                    "labeler_id": [f"rater_{idx % 3}" for idx, _ in enumerate(primary_ids)],
                    "label_notes": ["imported from sidecar"] * len(primary_ids),
                }
            ).to_csv(output_dir / "fig4_completed_blinded_labels.csv", index=False)
            answer_key.to_csv(output_dir / "fig4_blinded_labeling_answer_key.csv", index=False)

            rebuilt, _rebuilt_key, protocol = build_fig4_blinded_labeling_package(
                output_dir=output_dir,
                candidate_packet=packet,
                primary_per_tier=2,
                reserve_per_tier=1,
                seed=7,
            )
            audit = build_fig4_blinded_labeling_completion_audit(output_dir, min_primary_per_tier=2)

        rebuilt_primary = rebuilt[rebuilt["assignment_role"].eq("primary_validation_labeling_sample")]
        self.assertEqual({"completed_blinded_label_file"}, set(rebuilt_primary["label_source"].astype(str)))
        self.assertEqual({4}, set(pd.to_numeric(rebuilt_primary["label_novelty_1_5"]).astype(int)))
        self.assertEqual({5}, set(pd.to_numeric(rebuilt_primary["label_significance_1_5"]).astype(int)))
        self.assertEqual(1, int(audit["overall_blinded_labeling_ready"].max()))
        self.assertEqual("fig4_completed_blinded_labels.csv", protocol["completed_label_import_path"])

    def test_labeler_specific_blinded_label_returns_merge_when_complete(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet = pd.DataFrame(
                {
                    "paper_id": [f"d::https://openalex.org/W{i}" for i in range(18)],
                    "title": [f"Title {i}" for i in range(18)],
                    "domain": ["d"] * 18,
                    "year": [2010 + i for i in range(18)],
                    "primary_field": ["field"] * 18,
                    "fig3_score_for_validation": [float(i) for i in range(18)],
                    "fig3_global_percentile": [(i + 1) / 18 for i in range(18)],
                    "global_fig3_tier": ["low"] * 6 + ["middle"] * 6 + ["high"] * 6,
                }
            )
            blinded, _answer_key, protocol = build_fig4_blinded_labeling_package(
                output_dir=output_dir,
                candidate_packet=packet,
                primary_per_tier=2,
                reserve_per_tier=1,
                seed=7,
            )
            evaluator_templates = protocol["labeler_specific_completed_label_templates"]
            self.assertEqual(
                {
                    "labeler_1": "fig4_completed_blinded_labels_labeler_1.csv",
                    "labeler_2": "fig4_completed_blinded_labels_labeler_2.csv",
                    "labeler_3": "fig4_completed_blinded_labels_labeler_3.csv",
                },
                evaluator_templates,
            )
            primary_ids = list(
                blinded[blinded["assignment_role"].eq("primary_validation_labeling_sample")]["blinded_case_id"]
            )
            for labeler_id, file_name in evaluator_templates.items():
                rows = []
                for blind_id in primary_ids:
                    rows.append(
                        {
                            "blinded_case_id": blind_id,
                            "label_novelty_1_5": 4,
                            "label_significance_1_5": 5,
                            "label_prior_art_1_5": 3,
                            "label_confidence_1_5": 4,
                            "label_source": "external_blinded_human",
                            "labeler_id": labeler_id,
                            "label_notes": "complete independent return",
                        }
                    )
                pd.DataFrame(rows).to_csv(output_dir / file_name, index=False)

            merge_audit = merge_fig4_labeler_blinded_label_returns(output_dir)
            rebuilt, _rebuilt_key, _rebuilt_protocol = build_fig4_blinded_labeling_package(
                output_dir=output_dir,
                candidate_packet=packet,
                primary_per_tier=2,
                reserve_per_tier=1,
                seed=7,
            )
            completion_audit = build_fig4_blinded_labeling_completion_audit(output_dir, min_primary_per_tier=2)
            completed_labels_exists = (output_dir / "fig4_completed_blinded_labels.csv").exists()

        overall = merge_audit[merge_audit["audit_item"].eq("overall_labeler_return_merge_ready")].iloc[0]
        self.assertEqual(1, int(overall["pass"]))
        self.assertEqual(18, int(overall["observed_valid_labels"]))
        self.assertTrue(completed_labels_exists)
        rebuilt_primary = rebuilt[rebuilt["assignment_role"].eq("primary_validation_labeling_sample")]
        self.assertEqual(6, len(rebuilt_primary))
        self.assertEqual(1, int(completion_audit["overall_blinded_labeling_ready"].max()))

    def test_labeler_specific_blinded_label_returns_do_not_merge_blank_templates(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet = pd.DataFrame(
                {
                    "paper_id": [f"d::https://openalex.org/W{i}" for i in range(18)],
                    "title": [f"Title {i}" for i in range(18)],
                    "domain": ["d"] * 18,
                    "year": [2010 + i for i in range(18)],
                    "primary_field": ["field"] * 18,
                    "fig3_score_for_validation": [float(i) for i in range(18)],
                    "fig3_global_percentile": [(i + 1) / 18 for i in range(18)],
                    "global_fig3_tier": ["low"] * 6 + ["middle"] * 6 + ["high"] * 6,
                }
            )
            _blinded, _answer_key, protocol = build_fig4_blinded_labeling_package(
                output_dir=output_dir,
                candidate_packet=packet,
                primary_per_tier=2,
                reserve_per_tier=1,
                seed=7,
            )
            for file_name in protocol["labeler_specific_completed_label_templates"].values():
                table = pd.read_csv(output_dir / file_name)
                table.to_csv(output_dir / file_name, index=False)

            merge_audit = merge_fig4_labeler_blinded_label_returns(output_dir)

        overall = merge_audit[merge_audit["audit_item"].eq("overall_labeler_return_merge_ready")].iloc[0]
        self.assertEqual(0, int(overall["pass"]))
        self.assertEqual(0, int(overall["observed_valid_labels"]))
        self.assertFalse((output_dir / "fig4_completed_blinded_labels.csv").exists())

    def test_blinded_labeling_package_imports_completed_candidate_packet_labels(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            packet_rows = []
            for tier_idx, tier in enumerate(["low", "middle", "high"]):
                for offset in range(2):
                    packet_rows.append(
                        {
                            "paper_id": f"d::https://openalex.org/W{tier_idx}{offset}",
                            "title": f"{tier} title {offset}",
                            "domain": "d",
                            "year": 2010 + offset,
                            "primary_field": "field",
                            "fig3_score_for_validation": float(tier_idx * 10 + offset),
                            "fig3_global_percentile": [0.2, 0.7, 0.95][tier_idx],
                            "global_fig3_tier": tier,
                            "peer_novelty_human_1_5": 2 + tier_idx,
                            "peer_significance_human_1_5": 3 + tier_idx,
                            "peer_overall_human_1_5": 3 + tier_idx,
                            "label_source": "external_peer_label",
                            "labeler_id": f"peer_{offset}",
                            "label_notes": "label imported from completed candidate packet",
                        }
                    )

            blinded, _answer_key, _protocol = build_fig4_blinded_labeling_package(
                output_dir=output_dir,
                candidate_packet=pd.DataFrame(packet_rows),
                primary_per_tier=2,
                reserve_per_tier=0,
                seed=11,
            )
            audit = build_fig4_blinded_labeling_completion_audit(output_dir, min_primary_per_tier=2)

        self.assertEqual(6, len(blinded))
        self.assertEqual({"external_peer_label"}, set(blinded["label_source"].astype(str)))
        self.assertEqual({2, 3, 4}, set(pd.to_numeric(blinded["label_novelty_1_5"]).astype(int)))
        self.assertEqual({3, 4, 5}, set(pd.to_numeric(blinded["label_significance_1_5"]).astype(int)))
        self.assertEqual(1, int(audit["overall_blinded_labeling_ready"].max()))

    def test_extract_row_keywords_treats_nan_as_missing(self) -> None:
        row = {
            "keywords": float("nan"),
            "title": "Programmable genome editing with CRISPR systems",
            "abstract": "Genome editing systems enable targeted DNA modification.",
        }

        keywords = extract_row_keywords(row)

        self.assertNotIn("nan", keywords)
        self.assertIn("genome", keywords)
        self.assertLessEqual(len(extract_row_keywords(row, limit=3)), 3)

    def test_renderer_uses_matplotlib_orientation_keyword(self) -> None:
        source = (PROJECT_ROOT / "experiments/kg_perturbation_fig4/main_fig4.py").read_text(encoding="utf-8")

        self.assertNotIn("vert=", source)
        self.assertIn('orientation="horizontal"', source)


if __name__ == "__main__":
    unittest.main()
